# make zapp help files for crisp2
ZAPPDIR = /util2/zapp

crisp2.zhp: index.html readme.html faq.html info.html info1.html info2.html \
info3.html info4.html info5.html info6.html info7.html ch_manual.html \
intro.html intro1.html intro2.html intro3.html intro4.html intro5.html \
intro6.html users2.html users21.html users22.html users23.html users24.html \
users25.html users26.html users27.html users28.html users29.html users29a.html \
users29b.html users29c.html users29d.html users29d1.html users29e.html \
users29f.html users29g.html users29h.html lessons.html toc.html \
theory.mif2.html theory.mif4.html theory.mif5.html theory.mif6.html \
theory.mif7.html theory.mif9.html theory.mif10.html theory.mif11.html \
theory.mif12.html theory.mif13.html theory.mif14.html theory.mif15.html \
theory.mif16.html theory.mif17.html theory.mif18.html theory.mif20.html \
theory.mif21.html theory.mif22.html theory.mif23.html theory.mif24.html \
theory.mif25.html mapinfo.html
	$(ZAPPDIR)/bin/zhc -w0 index.html readme.html faq.html  \
info.html info1.html info2.html \
info3.html info4.html info5.html info6.html info7.html ch_manual.html \
intro.html intro1.html intro2.html intro3.html intro4.html intro5.html \
intro6.html users2.html users21.html users22.html users23.html users24.html \
users25.html users26.html users27.html users28.html users29.html users29a.html \
users29b.html users29c.html users29d.html users29d1.html users29e.html \
users29f.html users29g.html users29h.html lessons.html toc.html \
theory.mif2.html theory.mif4.html theory.mif5.html theory.mif6.html \
theory.mif7.html theory.mif9.html theory.mif10.html theory.mif11.html \
theory.mif12.html theory.mif13.html theory.mif14.html theory.mif15.html \
theory.mif16.html theory.mif17.html theory.mif18.html theory.mif20.html \
theory.mif21.html theory.mif22.html theory.mif23.html theory.mif24.html \
theory.mif25.html mapinfo.html
	cp index.hzhp crisp2.zhp
